/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Comidas` | `/Comidas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Ejercicios` | `/Ejercicios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Perfil` | `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Progreso` | `/Progreso`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/preferance`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Comidas` | `/Comidas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Ejercicios` | `/Ejercicios`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Perfil` | `/Perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Progreso` | `/Progreso`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/SignIn`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/preferance`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Comidas${`?${string}` | `#${string}` | ''}` | `/Comidas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Ejercicios${`?${string}` | `#${string}` | ''}` | `/Ejercicios${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Perfil${`?${string}` | `#${string}` | ''}` | `/Perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Progreso${`?${string}` | `#${string}` | ''}` | `/Progreso${`?${string}` | `#${string}` | ''}` | `/auth/SignIn${`?${string}` | `#${string}` | ''}` | `/auth/SignUp${`?${string}` | `#${string}` | ''}` | `/preferance${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Comidas` | `/Comidas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Ejercicios` | `/Ejercicios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Perfil` | `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Progreso` | `/Progreso`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/preferance`; params?: Router.UnknownInputParams; };
    }
  }
}
